---
driver:
  name: docker
  privileged: true
  use_sudo: false
  # For Podman, set DOCKER_HOST environment variable:
  # export DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock
  # Or use: export DOCKER_HOST=unix:///var/run/docker.sock

provisioner:
  name: chef_zero
  product_name: chef
  chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-22.04
    driver_config:
      image: ubuntu:22.04
      platform: ubuntu
      provision_command:
        - apt-get update
        - apt-get install -y sudo systemd systemd-sysv
        - apt-get install -y curl wget ca-certificates
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: ubuntu-20.04
    driver_config:
      image: ubuntu:20.04
      platform: ubuntu
      provision_command:
        - apt-get update
        - apt-get install -y sudo systemd systemd-sysv
        - apt-get install -y curl wget ca-certificates
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro

suites:
  - name: agent
    run_list:
      - recipe[axonops::agent_test]
    verifier:
      inspec_tests:
        - test/integration/agent
    attributes:
      axonops:
        agent:
          enabled: true
          type: "saas"
          key: "test-agent-key"
          organization: "test-org"