source 'https://rubygems.org'

gem 'chef', '~> 17.0'
gem 'chefspec', '~> 9.3'
gem 'test-kitchen', '~> 3.0'
gem 'kitchen-vagrant', '~> 1.12'
gem 'kitchen-docker', '~> 2.13'
gem 'kitchen-inspec', '~> 2.5'
gem 'cookstyle', '~> 7.0'
gem 'syslog'  # Required for Ruby 3.4+

# ChefSpec 9.3 requires rspec 3.9
group :test do
  gem 'rspec', '~> 3.9.0'
  gem 'rspec-core', '~> 3.9.0'
  gem 'rspec-expectations', '~> 3.9.0'
  gem 'rspec-mocks', '~> 3.9.0'
end
