name: Chef Unit Tests

on:
  push:
    branches: [ main, develop, test_units ]
  pull_request:
    branches: [ main, develop ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
        
    - name: Install Chef Workstation
      run: |
        wget https://packages.chef.io/files/stable/chef-workstation/23.5.1040/ubuntu/22.04/chef-workstation_23.5.1040-1_amd64.deb
        sudo dpkg -i chef-workstation_23.5.1040-1_amd64.deb

    - name: Install Chef
      run: |
        export CHEF_LICENSE=accept-silent
        export PATH=/opt/chef-workstation/bin:/opt/chef-workstation/embedded/bin:$PATH
        sudo apt-get -y install build-essential ruby-dev
        
        /opt/chef-workstation/embedded/bin/bundle install
      env:
        CHEF_LICENSE: accept-silent
        
    - name: Run RuboCop (linting)
      run: |
        export CHEF_LICENSE=accept-silent
        export PATH=/opt/chef-workstation/bin:/opt/chef-workstation/embedded/bin:$PATH
        /opt/chef-workstation/bin/chef exec rubocop --display-cop-names --extra-details
      continue-on-error: true
    
    - name: Run ChefSpec unit tests
      run: |
        export CHEF_LICENSE=accept-silent
        export PATH=/opt/chef-workstation/bin:/opt/chef-workstation/embedded/bin:$PATH
        /opt/chef-workstation/bin/chef exec rspec spec/unit/recipes/alert_rules_spec.rb --format documentation --color
    
    - name: Run all unit tests
      run: |
        export CHEF_LICENSE=accept-silent
        export PATH=/opt/chef-workstation/bin:/opt/chef-workstation/embedded/bin:$PATH
        /opt/chef-workstation/bin/chef exec rspec --format documentation --color
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: rspec-results-ruby-chef
        path: |
          coverage/
          .rspec_status
    
  cookstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        gem install cookstyle
        gem install chef
    
    - name: Run Cookstyle
      run: cookstyle --display-cop-names --extra-details
      continue-on-error: true
    
  foodcritic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        gem install foodcritic
        gem install chef
    
    - name: Run Foodcritic
      run: foodcritic . -f any -t ~FC121 -t ~FC034
      continue-on-error: true