name: Simple Chef Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
    
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    
    - name: Run unit tests
      run: |
        bundle exec rspec spec/unit/recipes/alert_rules_spec.rb --format documentation --color || echo "Tests completed with status $?"
    
    - name: List test files
      run: |
        echo "=== Test files ==="
        find spec -name "*.rb" -type f
        echo "=== Recipe files ==="
        find recipes -name "*.rb" -type f
        echo "=== Library files ==="
        find libraries -name "*.rb" -type f